#v = int(input('Введите число от 1 до 10: '))
#print(v + 10, end='\n')
#name = input('Введите ваше имя: ')
#print(f'Привет, {name}! Как дела?', end='\n')
print(float('1'))
print(int(float('2.5')))
print(bool(1))
print(bool(''))
print(bool(0))